### ISSUE TITLE
Refactor loading component (avoid using repetitive elements)

### ISSUE THREAD

**Issue by pandurijal** [pandurijal/react-giphy#7]
## Description
Basically what I need is just to refactor simple code on the loading component. What is already exist by now is 8 times of skeleton loading div, and needed to be changed by a javascript function that repeated this single div 8 times.

Notes: Expect no changes to the UI.

## Location
Go to this file `/src/Components/Loading.js`

## Hints
You can use `Array.from()` to repeat the element x times. Or if you want to use any other approach, just let me know.

**Comment by SMAKSS** [comment]
I will be happy to claim this one. 😁

**Comment by pandurijal** [comment]
Sure @SMAKSS go ahead!

**Comment by FajarSJ** [comment]
Hi @pandurijal, can i take this one too
